# Generated by Django 2.2.12 on 2021-08-06 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closeDoor', '0002_alter_door_open'),
    ]

    operations = [
        migrations.AlterField(
            model_name='door',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='door',
            name='open',
            field=models.BooleanField(),
        ),
    ]
