# Generated by Django 2.2.12 on 2021-08-18 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trash',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('type', models.CharField(max_length=15)),
                ('foreign_subst', models.BooleanField()),
                ('image', models.BinaryField()),
                ('feedback_type', models.CharField(max_length=15)),
                ('feedback_foreign_subst', models.BooleanField()),
            ],
        ),
    ]
