# Generated by Django 2.2.12 on 2021-08-19 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_trash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trash',
            name='foreign_subst',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='trash',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
