# Generated by Django 2.2.12 on 2021-08-19 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210819_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trash',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
