# Generated by Django 2.2.12 on 2021-08-19 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210819_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='trash',
            name='foreign_subst_probability',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trash',
            name='type_probability',
            field=models.IntegerField(default=0),
        ),
    ]
