# Generated by Django 2.2.12 on 2021-08-19 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210819_2037'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Trash',
        ),
    ]
