# Generated by Django 3.2.6 on 2021-08-20 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_trash_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trash',
            name='feedback_foreign_subst',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trash',
            name='feedback_type',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
