# Generated by Django 3.2.6 on 2021-08-20 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20210820_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trash',
            name='type_probability',
            field=models.FloatField(),
        ),
    ]
