# Generated by Django 3.2.6 on 2021-08-21 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_trash_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trash',
            name='image',
            field=models.CharField(max_length=300),
        ),
    ]
