# Generated by Django 3.2.6 on 2021-08-23 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_trash_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trash',
            name='feedback_type',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
